global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "opensearch"
    static_configs:
      - targets: ["opensearch:9200"]
    metrics_path: "/_prometheus/metrics"
    scrape_interval: 30s

  - job_name: "qdrant"
    static_configs:
      - targets: ["qdrant:6333"]
    metrics_path: "/metrics"
    scrape_interval: 30s
